config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "pages#index"

  resources :articles, :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Article
    unless user.blank?
        can :create, Article
        can [:update, :destroy], Article do |a|
            a.author == user
        end
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base

  default_scope { order(updated_at: :desc) }

  belongs_to :author, :class_name => "User"
  self.per_page = 20

  validates :title, :presence => {:message => "Please enter a title"}, :length => {:maximum => 40, :minimum => 3, :too_long => "Title can only be 40 characters long", :too_short => "Title must be 3 or more characters"}
  validates_presence_of :author_id, :message => "Please provide an Author"
  validates :formatted_text, :presence => {:message => "Please provide article content"}, :length => {:maximum => 2500, :minimum => 3, :too_long => "Article can only be 2500 characters long", :too_short => "Article must be 3 or more characters"}
  validates :plain_text, :presence => {:message => "Please provide article content"}, :length => {:maximum => 2500, :minimum => 3, :too_long => "Article can only be 2500 characters long", :too_short => "Article must be 3 or more characters"}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles, :class_name => "Article", :foreign_key => 'author_id'

  validates :first_name, :length => {:minimum => 2, :maximum => 25, :too_long => "First name must be 25 characters or less", :too_short => "First name must be 2 characters or more"}
  validates :last_name, :length => {:minimum => 2, :maximum => 25, :too_long => "Last name must be 25 characters or less", :too_short => "Last name must be 2 characters or more"}


  def name
    return self.first_name + " " + self.last_name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:first_name, :last_name, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource
  before_action :set_article, :only => [:show, :edit, :update, :destroy]
  helper FormatArticleHelper

  def index
    if params[:search].blank?
      @articles = Article.paginate(:page => params[:page])
    else
      @articles = Article.where("lower(title) LIKE ?", "%#{params[:search].downcase}%").paginate(:page => params[:page])
    end
    @index_articles= true
  end

  def show
    @new = false
  end

  def new
    @article = Article.new({
      :title => "Insert Title Here",
      :formatted_text => "Insert Article Contents Here"
    })
    @new = true
    render "articles/show"
  end

  def create
    @article = Article.new({
      :title => params[:title].strip,
      :plain_text => params[:plain_text].strip,
      :formatted_text => params[:formatted_text].strip,
      :author => current_user
      })
    if @article.save
      flash[:notice] = "Article Created Successfully"
      redirect_to article_path(:id => @article.id)
    else
      @new = true
      flash[:error] = @article.errors.full_messages
      render "articles/show"
    end
  end

  def update
    article = Article.find(params[:id])
    article.assign_attributes({
      :title => params[:title].strip,
      :plain_text => params[:plain_text].strip,
      :formatted_text => params[:formatted_text].strip
      })
    if article.save
      render :plain => "Article Updated Successfully", :status => 200
    else
      render :plain => "Article Update Failed : #{article.errors.full_messages}", :status => 503
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @articles = Article.order(:created_at).limit(5)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(date)
    unless date.nil?
      return date.strftime("%d/%m/%y")
    end
    return "-"
  end

  def text_limit(text, limit=100)
    if text.length > limit
      return text[0,97] + "..."
    else
      return text
    end
  end
end

app/helpers/format_article_helper.rb
module FormatArticleHelper
	def format_article(article)
		output_html = article.formatted_text
		unless output_html.blank?
			#Ensuring that the article formatting is the only executable HTML
			output_html.gsub!('<', '&lt;')
			output_html.gsub!('>', '&gt;')
			output_html.gsub!('[lb]', '<br>');
			#Series of string replacements for formatting
			#[b][/f] represents bold text
			output_html.gsub!('[b]', '<span class="bold-format">')
			output_html.gsub!('[/f]', "</span>")
			#[i][/f] represents italics text
			output_html.gsub!('[i]', '<span class="italic-format">')
			output_html.gsub!('[/f]', '</span>')
			#[t][/t] represents subtitle
			output_html.gsub!('[t]', '<h2>')
			output_html.gsub!('[/t]', '</h2>')
			#[code][/code] represents code		
			output_html.gsub!('[code]', '<div class="code">')
			output_html.gsub!('[/code]', '</div>')
			output_html.gsub!('[ct]', '<h3 class="code-title">')
			output_html.gsub!('[/ct]', '</h3>')
			return output_html.html_safe
		else
			return output_html
		end
	end
end

app/views/articles/_article_list.html.haml
%table.table.table-striped
  %thead
    %th
      Article Title
    %th
      Author
  %tbody
    -articles.each do |article|
      %tr
        %td
          =link_to article.title, article_path(article.id)
        %td
          =link_to article.author.name, user_path(article.author.id)
.pagination-wrapper
  =will_paginate articles

app/views/articles/index.html.haml
-content_for :title, "Articles"
%h1
  Articles
-unless @index_articles.nil?
  #search-articles.pull-right
    =form_tag({:controller => "articles", :action => "index"}, {:method => "get", :class => "form-horizontal"}) do
      .form-group
        .col-md-9.col-sd-12
          .col-md-3
            =label_tag :search, "Search: ", :class => "control-label"
          .col-md-9
            =text_field_tag :search, params[:search], :id => "search", :value => params[:search], :class => "form-control"
        .col-md-3.col-sd-12
          =button_tag :name => nil, :value => "Search", :class => "btn btn-default", :id => "search-btn" do
            Search
=render partial: "article_list", :locals => {:articles => @articles}

app/views/articles/show.html.haml
-content_for :title, (@new ? "New Article" : @article.title)
-content_editable = "false"
-article_class = ""
-if @new
  -content_editable = "true"
  -article_class = "editable"
#article{:class => article_class}
  -if can?(:update, @article) && !@new
    =hidden_field_tag "article-edit-url", article_path(@article.id) 
    #article-edit-button.pull-right{"contenteditable" => "false"}
      =link_to "javascript:Floow.Articles.editArticle();", :class => "btn btn-default", :id => "edit-button" do 
        Edit
      =link_to "javascript:Floow.Articles.updateArticle();", :class => "btn btn-primary hidden", :id => "save-button" do
        Save
  -elsif can?(:create, @article) && @new
    =form_tag @article, {:method => "POST", :id => "new-form"} do
      =hidden_field_tag "title", ""
      =hidden_field_tag "plain_text", ""
      =hidden_field_tag "formatted_text", ""
      .pull-right{"contenteditable" => "false"}
        =link_to "javascript:Floow.Articles.newArticle();", :class => "btn btn-primary", :id => "new-button" do
          Save
  %h1#article-title{"contenteditable" => content_editable}
    =@article.title
  -unless @new
    #article-details{"contenteditable" => "false"}
      =link_to @article.author.name, user_path(@article.author.id)
      =format_date(@article.created_at)
  #wysiwyg{:class => @new ? "" : "hidden"}
    =link_to "javascript:Floow.Articles.addCode();", :class => "btn btn-default", :id => "add-code" do
      %span.glyphicon.glyphicon-console{"aria-hidden" => "true"}
      Add Code
    =link_to "javascript:Floow.Articles.addBold();", :class => "btn btn-default", :id => "add-bold" do
      %span.glyphicon.glyphicon-bold{"aria-hidden" => "true"}
      Add Bold
    =link_to "javascript:Floow.Articles.addItalic();", :class => "btn btn-default", :id => "add-italic" do
      %span.glyphicon.glyphicon-italic{"aria-hidden" => "true"}
      Add Italics
    =link_to "javascript:Floow.Articles.addHeader();", :class => "btn btn-default", :id => "add-header" do
      %span.glyphicon.glyphicon-text-height{"aria-hidden" => "true"}
      Add Header
  #article-contents{"contenteditable" => content_editable}
    =format_article(@article)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title #{content_for(:title)} - Codewiki
    %meta(http-equiv='X-UA-Compatible' content='IE=edge')
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    = stylesheet_link_tag    "application", media: :all
    = javascript_include_tag "application"
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tags
    = yield :head 

  %body
    #page-wrapper
      %header
        %nav
          =link_to :root, :class => "navbar-brand" do
            =image_tag "floow-logo.png", :alt => "The Floow"
          %p{:align => "right"}
            -if user_signed_in?
              Welcome
              =current_user.first_name
              =link_to "Logout", destroy_user_session_path, :method => :delete
            -else
              =link_to "Login", new_user_session_path

      .flash-messages
        - flash.each do |name, msg|
          .alert.fade.in{ class: "alert-#{ name == 'notice' ? 'success' : 'danger' }" }
            %a.close{ data: { dismiss: :alert } } &times;
            = msg
      #body-wrapper.row
        #left-links.col-md-3.col-xs-12
          #page-logo
            =image_tag "floow-codewiki.png", :alt => "The Floow Code Wiki", :height => "120"
          %ul#links-list
            %li
              =link_to root_path do
                Latest Articles
            %li
              =link_to articles_path do
                Article Directory
            -if user_signed_in?
              %li
                =link_to user_path(current_user.id) do
                  My Articles
              %li
                =link_to new_article_path do
                  Write New Article



        #main-content.col-md-9.col-xs-12
          =yield
    %footer
      %p
        &copy; Shaun Smith for The Floow

app/views/pages/index.html.haml
-content_for :title, "Latest Articles"
%h1
  Latest Articles
-@articles.each do |article|
  .article
    %h3
      =link_to article.title, article_path(article.id)
    .article-list-details
      =article.author.name
    .article-snippet
      =text_limit(article.plain_text, 300)

app/views/users/show.html.haml
-content_for :title, @user.name + "'s articles"
%h1
  -if current_user == @user
    My Articles
  -else
    =@user.name+"'s Articles"
=render partial: "articles/article_list", :locals => {:articles => @user.articles.paginate(:page => params[:page])}